# This workflow will install Slips dependencies and run unit tests

name: CI-staging

on:
  push:
    branches:
    - 'develop'
    - '!master'
  pull_request:
    branches:
    - 'develop'
    - '!master'

jobs:

  run_unit_tests:
    # specify the host OS
    runs-on: ubuntu-latest
    # 2 hours timeout
    timeout-minutes: 7200
    # start a container using slips dependencies image
    container:
      image: alyagomaa/slips_dependencies:dependencies

    steps:
    - uses: actions/checkout@v2

    - name: Start redis server
      run: redis-server --daemonize yes

    - name: Run unit tests
      run: python3 -m pytest tests/ -p no:warnings -vv -s

