# This workflow will install Slips dependencies and run unit tests

name: CI

on:
  push:
    branches: [ master, develop, alya-CI ]
  pull_request:
    branches: [ master, develop, alya-CI  ]

jobs:

  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install slips dependencies
      run: sudo apt-get -y install curl git redis python3-redis python3-watchdog lsof file iptables wget tar

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install Python dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Node dependencies
      run: npm install blessed blessed-contrib redis async chalk \
          strip-ansi@6.0.0 clipboardy fs sorted-array-async yargs


    - name: Install Zeek
      run: |
        sudo apt-get -y install cmake make gcc g++ flex bison libpcap-dev libssl-dev python-dev swig zlib1g-dev
        git clone --recursive https://github.com/zeek/zeek
        cd zeek/
        ./configure
        sudo make
        sudo make install
        sudo ln --symbolic /usr/local/zeek/bin/zeek /usr/bin/zeek
        export PATH=$PATH:/usr/local/zeek/bin

    - name: Install YARA
      run: |
        wget https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.3.tar.gz
        tar -zxf v4.1.3.tar.gz
        cd yara-4.1.3
        ./bootstrap.sh
        ./configure
        make
        make install
        git clone https://github.com/VirusTotal/yara-python yara-python && cd yara-python
        python3 setup.py build && python3 setup.py install

    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0

    - name: start redis server
      run: redis-server --daemonize yes

  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clear the database
      run: ./slips.py -cc

    - name: Run unit tests
      run: python3 -m pytest tests/ --ignore="tests/test_dataset.py" -p no:warnings -vv

    - name: Test all files in our test_dataset
      run: python3 -m pytest tests/test_dataset.py -p no:warnings -vv -s